insert into public.phones (
  slug,
  name,
  brand,
  image_url,
  launch_status,
  release_date,
  price,
  best_price,
  affiliate_url,
  chipset,
  ram_gb,
  storage_gb,
  display,
  display_hz,
  battery_mah,
  charging_w,
  main_camera_mp,
  video,
  os,
  antutu_score,
  antutu_version,
  height_mm,
  width_mm,
  thickness_mm,
  weight_g,
  water_resistance,
  score_performance,
  score_camera,
  score_battery,
  score_display,
  score_build,
  score_value,
  verdict
) values
(
  'poco-x8-pro',
  'POCO X8 Pro',
  'Xiaomi',
  'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?q=80&w=600&auto=format&fit=crop',
  'available',
  '2026-02-10',
  2590,
  2399,
  'https://example.com/oferta-poco-x8-pro',
  'Dimensity 8400 Ultra',
  12,
  512,
  '6.67 AMOLED, 1.5K',
  120,
  5000,
  90,
  50,
  '4K',
  'Android 16 / HyperOS',
  1450000,
  'v11',
  162.9,
  77.9,
  8.1,
  218,
  'IP68',
  9.3,
  7.7,
  8.5,
  8.9,
  8.2,
  9.1,
  'Excelente para jogos e desempenho. Vale muito se estiver abaixo de R$ 2700.'
)
on conflict (slug) do nothing;

insert into public.phone_prices (phone_id, store, price, url)
select id, 'Mercado Livre', 2399, 'https://example.com/ml-poco'
from public.phones
where slug = 'poco-x8-pro'
on conflict do nothing;
