import type { Phone, PhonePrice } from "./types";

const extraSpecs = {
  gpu: "",
  ramType: "",
  storageType: "",
  screenType: "",
  screenResolution: "",
  ultrawideCameraMp: 0,
  telephotoCameraMp: 0,
  selfieCameraMp: 0,
  protection: "",
  nfc: true,
  fiveG: true,
  dualSim: true,
  esim: false,
  memoryCard: false,
  stereoSpeakers: true,
  audioJack: false,
  usbType: "USB-C",
  wifi: "",
  bluetooth: "",
  gps: "Sim",
  networkBands: "",
  pros: "",
  cons: "",
  publicationStatus: "published" as const,
  shortReview: "",
  recommendedFor: "",
  notRecommendedFor: "",
  alternatives: "",
  minHistoricalPrice: 0,
  lastPriceCheckedAt: "",
  screenSizeIn: 0,
  brightnessNits: 0,
  cameraSensor: "",
  hasOis: false,
  opticalZoom: "",
  updatePromise: "",
  biometricType: "",
  wirelessChargingW: 0,
  reverseCharging: false,
  editorialPriority: 0
};

export const phones: Phone[] = [
  {
    id: "poco-x8-pro",
    slug: "poco-x8-pro",
    name: "POCO X8 Pro",
    brand: "Xiaomi",
    imageUrl: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?q=80&w=600&auto=format&fit=crop",
    launchStatus: "available",
    releaseDate: "2026-02-10",
    price: 2590,
    bestPrice: 2399,
    affiliateUrl: "https://example.com/oferta-poco-x8-pro",
    chipset: "Dimensity 8400 Ultra",
    ramGb: 12,
    storageGb: 512,
    display: "6.67 AMOLED, 1.5K",
    displayHz: 120,
    batteryMah: 5000,
    chargingW: 90,
    mainCameraMp: 50,
    video: "4K",
    os: "Android 16 / HyperOS",
    antutuScore: 1450000,
    antutuVersion: "v11",
    heightMm: 162.9,
    widthMm: 77.9,
    thicknessMm: 8.1,
    weightG: 218,
    waterResistance: "IP68",
    ...extraSpecs,
    scorePerformance: 9.3,
    scoreCamera: 7.7,
    scoreBattery: 8.5,
    scoreDisplay: 8.9,
    scoreBuild: 8.2,
    scoreValue: 9.1,
    verdict: "Excelente para jogos e desempenho. Vale muito se estiver abaixo de R$ 2700."
  },
  {
    id: "galaxy-a56",
    slug: "galaxy-a56",
    name: "Samsung Galaxy A56 5G",
    brand: "Samsung",
    imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=600&auto=format&fit=crop",
    launchStatus: "available",
    releaseDate: "2025-03-18",
    price: 2199,
    bestPrice: 1899,
    affiliateUrl: "https://example.com/oferta-galaxy-a56",
    chipset: "Exynos 1580",
    ramGb: 8,
    storageGb: 256,
    display: "6.7 Super AMOLED+",
    displayHz: 120,
    batteryMah: 5000,
    chargingW: 45,
    mainCameraMp: 50,
    video: "4K",
    os: "Android 15 / One UI",
    antutuScore: 760000,
    antutuVersion: "v10",
    heightMm: 162.2,
    widthMm: 77.5,
    thicknessMm: 7.4,
    weightG: 198,
    waterResistance: "IP67",
    ...extraSpecs,
    scorePerformance: 7.5,
    scoreCamera: 8.2,
    scoreBattery: 8.2,
    scoreDisplay: 8.7,
    scoreBuild: 8.6,
    scoreValue: 8.3,
    verdict: "Equilibrado, bom sistema e camera consistente. Melhor para quem quer estabilidade."
  },
  {
    id: "oneplus-15",
    slug: "oneplus-15",
    name: "OnePlus 15",
    brand: "OnePlus",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=600&auto=format&fit=crop",
    launchStatus: "new",
    releaseDate: "2026-06-04",
    price: 4290,
    bestPrice: 3999,
    affiliateUrl: "https://example.com/oferta-oneplus-15",
    chipset: "Snapdragon 8 Elite",
    ramGb: 16,
    storageGb: 512,
    display: "6.82 LTPO AMOLED",
    displayHz: 144,
    batteryMah: 5400,
    chargingW: 100,
    mainCameraMp: 50,
    video: "8K",
    os: "Android 16 / OxygenOS",
    antutuScore: 2850000,
    antutuVersion: "v11",
    heightMm: 163.1,
    widthMm: 76.8,
    thicknessMm: 8.6,
    weightG: 214,
    waterResistance: "IP68",
    ...extraSpecs,
    scorePerformance: 9.9,
    scoreCamera: 8.8,
    scoreBattery: 9.0,
    scoreDisplay: 9.5,
    scoreBuild: 9.1,
    scoreValue: 8.0,
    verdict: "Topo de linha forte, mas so vira compra inteligente quando o preco cair."
  },
  {
    id: "iphone-17",
    slug: "iphone-17",
    name: "Apple iPhone 17",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?q=80&w=600&auto=format&fit=crop",
    launchStatus: "new",
    releaseDate: "2026-09-12",
    price: 8108,
    bestPrice: 7899,
    affiliateUrl: "https://example.com/oferta-iphone-17",
    chipset: "Apple A20",
    ramGb: 8,
    storageGb: 256,
    display: "6.3 OLED",
    displayHz: 120,
    batteryMah: 3650,
    chargingW: 30,
    mainCameraMp: 48,
    video: "4K Dolby Vision",
    os: "iOS 20",
    antutuScore: 2100000,
    antutuVersion: "v11",
    heightMm: 149.6,
    widthMm: 71.5,
    thicknessMm: 7.8,
    weightG: 178,
    waterResistance: "IP68",
    ...extraSpecs,
    scorePerformance: 9.6,
    scoreCamera: 9.1,
    scoreBattery: 7.8,
    scoreDisplay: 9.2,
    scoreBuild: 9.4,
    scoreValue: 6.8,
    verdict: "Excelente, mas caro. Compra emocional ou para quem quer iOS sem discussao."
  }
];

export const prices: PhonePrice[] = [
  { id: "1", phoneId: "poco-x8-pro", store: "Amazon", price: 2590, url: "https://example.com/amazon-poco", updatedAt: "2026-06-20", coupon: "", cashback: "", inStock: true, trustedStore: true },
  { id: "2", phoneId: "poco-x8-pro", store: "Mercado Livre", price: 2399, url: "https://example.com/ml-poco", updatedAt: "2026-06-20", coupon: "", cashback: "", inStock: true, trustedStore: true },
  { id: "3", phoneId: "galaxy-a56", store: "Magalu", price: 1899, url: "https://example.com/magalu-a56", updatedAt: "2026-06-20", coupon: "", cashback: "", inStock: true, trustedStore: true },
  { id: "4", phoneId: "oneplus-15", store: "Importador", price: 3999, url: "https://example.com/oneplus", updatedAt: "2026-06-20", coupon: "", cashback: "", inStock: true, trustedStore: true }
];
