export type Phone = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  imageUrl: string;
  launchStatus: "available" | "rumor" | "new";
  publicationStatus: "draft" | "review" | "published" | "archived";
  releaseDate: string;
  price: number;
  bestPrice: number;
  affiliateUrl: string;
  chipset: string;
  gpu: string;
  ramGb: number;
  ramType: string;
  storageGb: number;
  storageType: string;
  display: string;
  screenType: string;
  screenResolution: string;
  displayHz: number;
  batteryMah: number;
  chargingW: number;
  mainCameraMp: number;
  ultrawideCameraMp: number;
  telephotoCameraMp: number;
  selfieCameraMp: number;
  video: string;
  os: string;
  antutuScore: number;
  antutuVersion: string;
  heightMm: number;
  widthMm: number;
  thicknessMm: number;
  weightG: number;
  waterResistance: string;
  protection: string;
  nfc: boolean;
  fiveG: boolean;
  dualSim: boolean;
  esim: boolean;
  memoryCard: boolean;
  stereoSpeakers: boolean;
  audioJack: boolean;
  usbType: string;
  wifi: string;
  bluetooth: string;
  gps: string;
  networkBands: string;
  pros: string;
  cons: string;
  scorePerformance: number;
  scoreCamera: number;
  scoreBattery: number;
  scoreDisplay: number;
  scoreBuild: number;
  scoreValue: number;
  shortReview: string;
  recommendedFor: string;
  notRecommendedFor: string;
  alternatives: string;
  minHistoricalPrice: number;
  lastPriceCheckedAt: string;
  screenSizeIn: number;
  brightnessNits: number;
  cameraSensor: string;
  hasOis: boolean;
  opticalZoom: string;
  updatePromise: string;
  biometricType: string;
  wirelessChargingW: number;
  reverseCharging: boolean;
  editorialPriority: number;
  verdict: string;
};

export type PhonePrice = {
  id: string;
  phoneId: string;
  store: string;
  price: number;
  url: string;
  updatedAt: string;
  coupon: string;
  cashback: string;
  inStock: boolean;
  trustedStore: boolean;
};

export type UserProfile = {
  id: string;
  role: "user" | "editor" | "admin" | "owner";
  fullName: string;
  phone: string;
  city: string;
  state: string;
  budgetMin: number;
  budgetMax: number;
  preferredBrands: string[];
  wantsOffers: boolean;
};
